version: '3.8'

services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host=0.0.0.0 --port=8000
db:
    image: mysql:latest
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    restart: always
